services:
  mariadbserver:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M4r14DB123#$
      MYSQL_DATABASE: lab_devops
      MYSQL_USER: cordovar
      MYSQL_PASSWORD: M4r14DB123#$
    
  phpmyadminserver:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadbserver
      MYSQL_ROOT_PASSWORD: Php4dm1n123#$
    ports:
      - "8081:80"